language: python

python:
  - 3.3
  - 3.4

install:
  - pip install cairocffi
  - pip install tinycss
  - pip install cssselect
  - pip install lxml
  - pip install pillow

before_script:
  - mkdir ~/.fonts
  - cp ./test/resources/*.*tf ~/.fonts
  - fc-cache -f -v

script: nosetests

sudo: false
