language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

install:
  - pip install cairocffi
  - pip install nose
  - pip install tinycss
  - pip install cssselect
  - pip install lxml
  - pip install pillow

before_script:
  - mkdir ~/.fonts
  - cp ./test/resources/*.ttf ~/.fonts
  - fc-cache -f -v
  - python -c "import cairocffi;print(cairocffi.cairo_version_string())"

script: nosetests

sudo: false
