language: python
sudo: false

matrix:
  include:
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - dist: xenial
      python: 3.7

install:
  - pip install --upgrade -e.[test]

before_script:
  - mkdir ~/.fonts
  - cp ./test_non_regression/resources/*.*tf ~/.fonts
  - fc-cache -f -v

script:
  - python setup.py test
