name: CairoSVG
description: Convert SVG to PNG or PDF
license: LGPLv3
public: true
url: http://www.cairosvg.org/
pystil: https://kozea.pystil.org/pystil.js

menu:
  - News:
      link: /news/
  - Documentation:
      link: /documentation/
  - Contribute:
      link: /contribute/
  - Download:
      link: /download/

footer:
  - A Kozea Project:
      link: http://community.kozea.fr/
  - Optimized for Standards:
      link: http://validator.w3.org/check?uri=referer

project (git):
  url: git://github.com/Kozea/CairoSVG.git
  path: cairosvg

code browser (github):
  project name: Kozea/CairoSVG
  ribbon: Fork me on GitHub

bug tracker (github):
  project name: Kozea/CairoSVG

continuous integration (jenkins):
  base url: http://jenkins.kozea.org/
  project name: CairoSVG
